name: Sync to Hugging Face Spaces
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  HF_SPACE: renzungo/clarin-sentiment-dashboard

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git
        run: |
          git lfs install
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote remove hf 2>/dev/null || true
          git remote add hf https://huggingface.co/spaces/$HF_SPACE
          git -c http.extraHeader="Authorization: Bearer $HF_TOKEN" push --force hf HEAD:main
