name: Sync to Hugging Face Spaces
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set git identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Space (direct URL + auth header)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: renzungo/clarin-sentiment-dashboard
        run: |
          set -e
          git -c http.extraHeader="Authorization: Bearer $HF_TOKEN" \
              push --force https://huggingface.co/spaces/$HF_SPACE HEAD:main
